"""Generate human indexes from files and the source registry; no model calls."""
from setup import ROOT, atomic, read_json


def render():
    lines = ["# Documentation index", "", "Generated by scripts/index_docs.py. Do not edit the file list manually.", ""]
    for path in sorted((ROOT / "docs").rglob("*.md")):
        if path.name == "index.md":
            continue
        relative = path.relative_to(ROOT / "docs").as_posix()
        title = path.read_text(encoding="utf-8").splitlines()[0].lstrip("# ")
        lines.append(f"- [{title}]({relative})")
    lines += ["", "## Source decisions", "", "| ID | Source | Disposition |", "|---|---|---|"]
    for source in read_json(ROOT / "references/registry.json")["sources"]:
        lines.append(f'| {source["id"]} | [Source]({source.get("canonical_url", source["url"])}) | {source["disposition"]} |')
    return ("\n".join(lines) + "\n").encode()


def main():
    atomic(ROOT / "docs/index.md", render())


if __name__ == "__main__":
    main()
